default_install_hook_types:
  - prepare-commit-msg
repos:
  - repo: https://github.com/moreh-dev/pre-commit-hooks
    rev: v0.5.1
    hooks:
      - id: add-jira-issue-key-to-commit-msg
        args:
          - --key
          - MAF
          - --enable-no-issue
